FROM node:22-alpine

WORKDIR /app

RUN npm install -g @solid/community-server@8.0.0-alpha.3

ENV CSS_CONFIG=@css:config/file-root.json
ENV CSS_BASE_URL=http://localhost:3000/

EXPOSE 3000

CMD ["sh", "-c", "community-solid-server -p=3000 -b=\"$CSS_BASE_URL\" -c=\"$CSS_CONFIG\" -f=/data"]
