FROM node:22-alpine

WORKDIR /app

RUN npm install -g @solid/community-server@8.0.0-alpha.3

COPY containerization/solid-pod-tls-proxy.js /app/solid-pod-tls-proxy.js

ENV CSS_CONFIG=@css:config/file-root.json
ENV CSS_BASE_URL=https://localhost:3000/
ENV CSS_HTTP_PORT=3001
ENV TLS_PORT=3000

EXPOSE 3000

CMD ["sh", "-c", "community-solid-server -p=\"$CSS_HTTP_PORT\" -b=\"$CSS_BASE_URL\" -c=\"$CSS_CONFIG\" -f=/data & node /app/solid-pod-tls-proxy.js"]
